# Generated by Django 6.0.7 on 2026-07-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_adjustment', models.SmallIntegerField(choices=[(-1, '-১ দিন'), (0, 'সমন্বয় নেই'), (1, '+১ দিন')], default=0, help_text='বাংলাদেশের চাঁদ দেখা অনুযায়ী হিজরি তারিখ সমন্বয়')),
            ],
            options={
                'verbose_name': 'সাইট কনফিগারেশন',
            },
        ),
    ]
